dist: trusty
sudo: required
language: node_js
node_js:
- node
addons:
  postgresql: '9.6'
services:
- docker
- postgresql
env:
  DATABASE_URL: postgres://postgres@localhost/travis?ssl=false
  DOCKER_USERNAME: smashwilson
  global:
    secure: PNCC+XXy/MekvaeBCmIoJfUn9S8aGfV0ncKxOTI8K8X4UAGHRVem7TpfgGOyNGWO08Z5AJeqmt3n2pXBD47BBkSJuE568pDLb+Hy8hni6a7BShRGIqxXxl6omNCbloNM0VJU8vqSWzSbsVwYTnKo/e/71/GLi7IeZFPyU3rMVrg=
script:
- bin/ci/test
after_success:
- bin/ci/push
notifications:
  email: false
