version: '2'
services:
  redis:
    image: redis
  pushbot:
    build: .
    volumes:
    - ".:/usr/src/app/"
    environment:
      REDISTOGO_URL: redis://redis/
      HUBOT_SLACK_TOKEN:
      HUBOT_MARKOV_LEARN_MIN:
      HUBOT_MARKOV_GENERATE_MAX:
      HUBOT_QUOTEFILE_PATH:
      HUBOT_AUTH_ADMIN:
      HUBOT_BETRAY_IMMUNE:
      HUBOT_MAPPING_DATAROOT:
      HUBOT_WEATHER_APIKEY:
      HUBOT_LISTS_ROOT:
    depends_on:
    - redis
